export const TEST_USERS = [
  {
    id: "1",
    email: "john.doe@example.com",
    name: "John Doe",
    role: "doctor",
    password: "password",
  },
  {
    id: "2",
    email: "jane.smith@example.com",
    name: "Jane Smith",
    role: "patient",
    password: "password",
  },
  {
    id: "3",
    email: "robert.jones@example.com",
    name: "Robert Jones",
    role: "admin",
    password: "password",
  },
  {
    id: "4",
    email: "alice.brown@example.com",
    name: "Alice Brown",
    role: "doctor",
    password: "password",
  },
  {
    id: "5",
    email: "michael.davis@example.com",
    name: "Michael Davis",
    role: "patient",
    password: "password",
  },
  {
    id: "6",
    email: "linda.wilson@example.com",
    name: "Linda Wilson",
    role: "admin",
    password: "password",
  },
  {
    id: "7",
    email: "david.garcia@example.com",
    name: "David Garcia",
    role: "doctor",
    password: "password",
  },
  {
    id: "8",
    email: "susan.rodriguez@example.com",
    name: "Susan Rodriguez",
    role: "patient",
    password: "password",
  },
  {
    id: "9",
    email: "secretaria@clinica.com",
    name: "María Secretaria",
    role: "secretary",
    password: "secretaria",
  },
  {
    id: "10",
    email: "recepcion@clinica.com",
    name: "Carmen Recepción",
    role: "secretary",
    password: "recepcion",
  },
]
